apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: pluck
profiles:
  - name: dev
    activation:
    - env: RAILS_ENV=development
      command: dev
    build:
      tagPolicy:
        gitCommit:
          prefix: dev-
      local: {}
      artifacts:
      - image: localhost/pluck
        docker:
          dockerfile: Dockerfile
          buildArgs:
            RAILS_ENV: '{{.RAILS_ENV}}'
        sync:
          # infer:
          #   - '**'
          manual:
            - src: "*/**"
              dest: .
    deploy:
      helm:
        flags:
          install:
            - --create-namespace
          upgrade:
            - --install
            - --create-namespace
        releases:
        - name: pluck-web
          useHelmSecrets: true
          namespace: pluck
          chartPath: ../layerkeep-infra/charts/pluck/pluck-web
          wait: true
          artifactOverrides:
            image: localhost/pluck
          #   image: localhost/pluck:5baa5553
          # values:
          #   image: layerkeep
          # setValues:
          #   image.repository: layerkeep
          #   image: registry.digitalocean.com/frenzylabs/pluck:5baa5553
          valuesFiles:
              - ../layerkeep-infra/charts/pluck/pluck-web/values.yaml
              - ../layerkeep-infra/charts/pluck/pluck-web/values.local.yaml
              - ./values.local.yaml
              - ../layerkeep-infra/secrets/secrets.local.yaml
          imageStrategy:
            helm: {}

    portForward:
      - resourceType: service
        namespace: pluck
        resourceName: pluck-web
        port: 80
        localPort: 3001
