version: '3'
services:
  pluck:
    container_name: pluck-devcontainer
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    image: "localhost/ruby-devcontainer:latest"
    volumes:
      # Mount the root folder that contains .git
      - ../:/frenzylabs/pluck
      - ../../layerkeep-infra:/frenzylabs/layerkeep-infra:cached
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${HOME}/.kube:/root/.kube
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.aws:/root/.aws
      - ${HOME}/.saml2aws:/root/.saml2aws
      - ${HOME}/.gnupg:/root/.gnupg
      - ${HOME}/.config:/root/.config
      - pluck-bashhistory:/commandhistory
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      PG_HOST: host.docker.internal
      PG_USERNAME: ${PG_USERNAME:-postgres}
      PG_PASSWORD: ${PG_PASSWORD:-''}
      PG_DATABASE: ${PG_DATABASE:-layerkeep}
      # DIGITALOCEAN_ACCESS_TOKEN: ${DIGITALOCEAN_ACCESS_TOKEN:-''}

    # ...

volumes: 
  pluck-bashhistory:
